# Gen by grok + chatgpt
cot_templates_grok = [
    "By observing the image carefully. I see that:\n {circle_descriptions}. So the conclusion is: Since the number of circles is {num_circles}, which is an {parity} number, the answer is {parity}",
    "After analyzing the image, I notice:\n {circle_descriptions}. Thus, with {num_circles} circles, the answer is {parity}",
    "Examining the image closely, I count:\n {circle_descriptions}. This gives {num_circles} circles, so the answer is {parity}",
    "Upon inspecting the image, I identify:\n {circle_descriptions}. Therefore, with a total of {num_circles}, the result is {parity}",
    "Looking at the image in detail, I observe:\n {circle_descriptions}. This leads to {num_circles} circles, concluding the answer is {parity}",
    "By carefully studying the image, I find:\n {circle_descriptions}. Hence, since there are {num_circles} circles, the answer is {parity}",
    "Analyzing the visual data, I detect:\n {circle_descriptions}. With {num_circles} circles counted, the answer is {parity}",
    "While reviewing the image, I note:\n {circle_descriptions}. This totals {num_circles} circles, so the answer is {parity}",
    "Through close observation, I see:\n {circle_descriptions}. Given {num_circles} circles, the outcome is {parity}",
    "Inspecting each part of the image, I record:\n {circle_descriptions}. Thus, with {num_circles} circles, the answer is {parity}",
    "By scanning the image thoroughly, I discover:\n {circle_descriptions}. This results in {num_circles} circles, leading to {parity}",
    "After a detailed look, I identify:\n {circle_descriptions}. With {num_circles} circles present, the answer is {parity}",
    "Observing the image step by step, I count:\n {circle_descriptions}. This yields {num_circles} circles, so the answer is {parity}",
    "By evaluating the image, I notice:\n {circle_descriptions}. Therefore, {num_circles} circles indicate a {parity} answer",
    "Studying the image carefully, I detect:\n {circle_descriptions}. With a count of {num_circles}, the result is {parity}",
    "Upon close examination, I see:\n {circle_descriptions}. This gives {num_circles} circles, concluding with {parity}",
    "Analyzing the image’s contents, I find:\n {circle_descriptions}. Hence, {num_circles} circles lead to a {parity} outcome",
    "By reviewing the visual elements, I observe:\n {circle_descriptions}. With {num_circles} circles, the answer is {parity}",
    "Inspecting the image with care, I count:\n {circle_descriptions}. This totals {num_circles} circles, resulting in {parity}",
    "After thorough analysis, I identify:\n {circle_descriptions}. Given {num_circles} circles, the final answer is {parity}",
    "By exploring the image, I spot:\n {circle_descriptions}. Thus, {num_circles} circles suggest a {parity} result",
    "Carefully assessing the image, I note:\n {circle_descriptions}. With {num_circles} circles, the answer is {parity}",
    "Through detailed inspection, I observe:\n {circle_descriptions}. This confirms {num_circles} circles, leading to {parity}",
    "Analyzing the image step-by-step, I see:\n {circle_descriptions}. Hence, {num_circles} circles yield a {parity} answer",
    "By examining the visual layout, I count:\n {circle_descriptions}. This gives {num_circles} circles, so the answer is {parity}",
    "Studying the image closely, I detect:\n {circle_descriptions}. Therefore, with {num_circles}, the result is {parity}",
    "Upon reviewing the image, I identify:\n {circle_descriptions}. With a total of {num_circles}, the answer is {parity}",
    "By observing each detail, I find:\n {circle_descriptions}. This leads to {num_circles} circles, concluding {parity}",
    "Analyzing the image’s structure, I note:\n {circle_descriptions}. Thus, {num_circles} circles indicate {parity}",
    "Through careful scrutiny, I see:\n {circle_descriptions}. With {num_circles} circles, the outcome is {parity}",
    "Inspecting the image thoroughly, I record:\n {circle_descriptions}. This totals {num_circles}, resulting in {parity}",
    "By assessing the image, I discover:\n {circle_descriptions}. Hence, {num_circles} circles lead to {parity}",
    "After close analysis, I observe:\n {circle_descriptions}. With {num_circles} counted, the answer is {parity}",
    "Examining the image with focus, I find:\n {circle_descriptions}. This yields {num_circles} circles, so {parity}",
    "By reviewing the image’s elements, I see:\n {circle_descriptions}. Thus, {num_circles} circles give {parity}",
    "Analyzing each section, I count:\n {circle_descriptions}. With {num_circles}, the result is {parity}",
    "Through detailed observation, I note:\n {circle_descriptions}. This confirms {num_circles} circles, leading to {parity}",
    "By inspecting the image closely, I detect:\n {circle_descriptions}. Hence, {num_circles} circles suggest {parity}",
    "Studying the visual content, I identify:\n {circle_descriptions}. With {num_circles}, the answer is {parity}",
    "Upon careful review, I see:\n {circle_descriptions}. This totals {num_circles} circles, resulting in {parity}",
    "By analyzing the image’s details, I find:\n {circle_descriptions}. Thus, {num_circles} circles lead to {parity}",
    "Examining the image step by step, I count:\n {circle_descriptions}. This gives {num_circles}, so the answer is {parity}",
    "Through close inspection, I observe:\n {circle_descriptions}. With {num_circles} circles, the outcome is {parity}",
    "By evaluating the image, I note:\n {circle_descriptions}. Hence, {num_circles} circles indicate {parity}",
    "Analyzing the visual pattern, I see:\n {circle_descriptions}. This yields {num_circles} circles, concluding {parity}",
    "By studying the image carefully, I detect:\n {circle_descriptions}. With {num_circles}, the result is {parity}",
    "Upon thorough examination, I identify:\n {circle_descriptions}. Thus, {num_circles} circles give {parity}",
    "Through detailed analysis, I count:\n {circle_descriptions}. This totals {num_circles}, leading to {parity}",
    "By reviewing the image’s layout, I find:\n {circle_descriptions}. Hence, {num_circles} circles suggest {parity}",
    "Inspecting the image with precision, I see:\n {circle_descriptions}. With {num_circles}, the answer is {parity}",
    "After analyzing the image’s content, I note:\n {circle_descriptions}. This gives {num_circles} circles, so {parity}",
    "By observing the image’s structure, I detect:\n {circle_descriptions}. Thus, {num_circles} circles lead to {parity}",
    "Examining each element, I count:\n {circle_descriptions}. With {num_circles}, the result is {parity}",
    "Through careful evaluation, I see:\n {circle_descriptions}. This yields {num_circles} circles, concluding {parity}",
    "By inspecting the visual data, I find:\n {circle_descriptions}. Hence, {num_circles} circles indicate {parity}",
    "Analyzing the image step-by-step, I note:\n {circle_descriptions}. With {num_circles}, the answer is {parity}",
    "Upon close scrutiny, I observe:\n {circle_descriptions}. This totals {num_circles} circles, resulting in {parity}",
    "By reviewing the image’s details, I detect:\n {circle_descriptions}. Thus, {num_circles} circles give {parity}",
    "Studying the image with care, I count:\n {circle_descriptions}. This leads to {num_circles}, so the answer is {parity}",
    "Through detailed inspection, I see:\n {circle_descriptions}. With {num_circles} circles, the outcome is {parity}",
    "By analyzing the visual elements, I find:\n {circle_descriptions}. Hence, {num_circles} circles suggest {parity}",
    "Examining the image closely, I note:\n {circle_descriptions}. This yields {num_circles} circles, concluding {parity}",
    "By observing the image’s content, I detect:\n {circle_descriptions}. With {num_circles}, the result is {parity}",
    "Upon thorough analysis, I identify:\n {circle_descriptions}. Thus, {num_circles} circles lead to {parity}",
    "Through careful review, I count:\n {circle_descriptions}. This totals {num_circles}, resulting in {parity}",
    "By inspecting the image’s layout, I see:\n {circle_descriptions}. Hence, {num_circles} circles indicate {parity}",
    "Analyzing each part, I note:\n {circle_descriptions}. With {num_circles}, the answer is {parity}",
    "By studying the visual pattern, I find:\n {circle_descriptions}. This gives {num_circles} circles, so {parity}",
    "Through close examination, I detect:\n {circle_descriptions}. Thus, {num_circles} circles lead to {parity}",
    "By evaluating the image’s structure, I count:\n {circle_descriptions}. With {num_circles}, the result is {parity}",
    "Upon detailed analysis, I observe:\n {circle_descriptions}. This yields {num_circles} circles, concluding {parity}",
    "By reviewing the image with care, I see:\n {circle_descriptions}. Hence, {num_circles} circles suggest {parity}",
    "Examining the visual data, I note:\n {circle_descriptions}. With {num_circles}, the answer is {parity}",
    "Through thorough inspection, I find:\n {circle_descriptions}. This totals {num_circles} circles, resulting in {parity}",
    "By analyzing the image’s elements, I detect:\n {circle_descriptions}. Thus, {num_circles} circles give {parity}",
    "Studying the image step-by-step, I count:\n {circle_descriptions}. This leads to {num_circles}, so the answer is {parity}",
    "Upon close observation, I see:\n {circle_descriptions}. With {num_circles} circles, the outcome is {parity}",
    "By inspecting the image’s details, I note:\n {circle_descriptions}. Hence, {num_circles} circles indicate {parity}",
    "Analyzing the visual layout, I find:\n {circle_descriptions}. With {num_circles}, the result is {parity}",
    "Through careful scrutiny, I detect:\n {circle_descriptions}. This yields {num_circles} circles, concluding {parity}",
    "By reviewing the image’s content, I count:\n {circle_descriptions}. Thus, {num_circles} circles lead to {parity}",
    "Examining the image with precision, I see:\n {circle_descriptions}. With {num_circles}, the answer is {parity}",
    "By observing each element, I note:\n {circle_descriptions}. This totals {num_circles} circles, resulting in {parity}",
    "Through detailed evaluation, I find:\n {circle_descriptions}. Hence, {num_circles} circles suggest {parity}",
    "By analyzing the image’s pattern, I detect:\n {circle_descriptions}. With {num_circles}, the result is {parity}",
    "Upon thorough review, I count:\n {circle_descriptions}. This gives {num_circles} circles, so the answer is {parity}",
    "Studying the visual structure, I see:\n {circle_descriptions}. Thus, {num_circles} circles lead to {parity}"
]

cot_templates_chatgpt = [
    "By carefully examining the image, I identify:\n {circle_descriptions}. Therefore, since there are {num_circles} circles, which is an {parity} number, the conclusion is {parity}.",
    "Upon detailed observation, I note:\n {circle_descriptions}. Hence, the total is {num_circles}, and because that is an {parity} number, the final answer is {parity}.",
    "Looking at the image step by step, I observe:\n {circle_descriptions}. Adding them gives {num_circles}, which is {parity}, so the outcome is {parity}.",
    "Through inspection, I detect:\n {circle_descriptions}. This sums to {num_circles} circles. Since {num_circles} is {parity}, the result is {parity}.",
    "After analyzing the visual elements, I list:\n {circle_descriptions}. That means there are {num_circles} in total, and because {num_circles} is {parity}, the answer is {parity}.",
    "From close scrutiny, I find:\n {circle_descriptions}. Altogether, that gives {num_circles} circles, which is {parity}, so the solution is {parity}.",
    "Examining carefully, I count:\n {circle_descriptions}. This results in {num_circles}. Since {num_circles} is {parity}, the conclusion follows: {parity}.",
    "By analyzing one by one, I see:\n {circle_descriptions}. In total, we get {num_circles}, and being an {parity} number, the answer is {parity}.",
    "Observing systematically, the image contains:\n {circle_descriptions}. That’s {num_circles} circles, which is {parity}, hence the final answer is {parity}.",
    "When I check thoroughly, I detect:\n {circle_descriptions}. These add to {num_circles}. Because {num_circles} is {parity}, the answer must be {parity}.",
    "Looking in detail, I can enumerate:\n {circle_descriptions}. That means the count is {num_circles}. As {num_circles} is {parity}, the result is {parity}.",
    "Breaking it down, I observe:\n {circle_descriptions}. The sum is {num_circles}. Since that is {parity}, the conclusion is {parity}.",
    "Upon reasoning carefully, the circles are:\n {circle_descriptions}. Their total is {num_circles}, which is {parity}, so the answer is {parity}.",
    "From inspection, the observations are:\n {circle_descriptions}. Thus, the count is {num_circles}. As {num_circles} is {parity}, the output is {parity}.",
    "Looking attentively, I note down:\n {circle_descriptions}. Summing gives {num_circles}, which qualifies as {parity}, hence the answer is {parity}.",
    "By reasoning step by step, I find:\n {circle_descriptions}. These account for {num_circles} circles. Since that number is {parity}, the result is {parity}.",
    "Upon precise analysis, I see:\n {circle_descriptions}. The total is {num_circles}, which is {parity}, so the final decision is {parity}.",
    "Studying the image, I realize:\n {circle_descriptions}. Counting them results in {num_circles}, which is {parity}, therefore the answer is {parity}.",
    "Examining logically, I conclude:\n {circle_descriptions}. This equals {num_circles}, and since {num_circles} is {parity}, the correct answer is {parity}.",
    "After systematic observation, I detect:\n {circle_descriptions}. Altogether, there are {num_circles}. Being {parity}, the answer is {parity}.",
    "Careful review reveals:\n {circle_descriptions}. These add to {num_circles}. Given {num_circles} is {parity}, the solution is {parity}.",
    "Analyzing with reasoning, I record:\n {circle_descriptions}. The overall count is {num_circles}, which is {parity}, leading to {parity}.",
    "From close study, I observe:\n {circle_descriptions}. In total, {num_circles}. Because that’s {parity}, the conclusion is {parity}.",
    "Through careful analysis, the findings are:\n {circle_descriptions}. That equals {num_circles} circles, which is {parity}, hence the answer is {parity}.",
    "When reasoning stepwise, I identify:\n {circle_descriptions}. Their sum is {num_circles}. Since {num_circles} is {parity}, the answer must be {parity}.",
    "A closer look shows:\n {circle_descriptions}. So the total number of circles is {num_circles}, which is {parity}, making the result {parity}.",
    "Step by step, I determine:\n {circle_descriptions}. The total count is {num_circles}, which is {parity}, and thus the outcome is {parity}.",
    "By counting carefully, I find:\n {circle_descriptions}. This means {num_circles} circles exist. Since that’s {parity}, the conclusion is {parity}.",
    "After reasoning, I gather:\n {circle_descriptions}. Therefore, {num_circles} in total, and being {parity}, the answer is {parity}.",
    "Examining logically, I tally:\n {circle_descriptions}. The result is {num_circles}. Since {num_circles} is {parity}, the answer becomes {parity}.",
    "Detailed analysis shows:\n {circle_descriptions}. This yields {num_circles}, which is {parity}, so the conclusion is {parity}.",
    "From systematic reasoning, I count:\n {circle_descriptions}. That adds to {num_circles}. As this is {parity}, the output is {parity}.",
    "Inspecting in detail, I mark:\n {circle_descriptions}. Their total count is {num_circles}, which is {parity}, giving the final answer {parity}.",
    "By careful reasoning, I identify:\n {circle_descriptions}. These sum to {num_circles}. Since {num_circles} is {parity}, the solution is {parity}.",
    "Logical breakdown reveals:\n {circle_descriptions}. Therefore, {num_circles} circles in total, which is {parity}, so the conclusion is {parity}.",
    "Looking frame by frame, I observe:\n {circle_descriptions}. Summing gives {num_circles}. As this is {parity}, the answer is {parity}.",
    "Through detailed review, I list:\n {circle_descriptions}. Their count is {num_circles}, which is {parity}, and so the result is {parity}.",
    "Reasoning carefully, I gather:\n {circle_descriptions}. Altogether there are {num_circles}, which is {parity}, hence the solution is {parity}.",
    "After methodical analysis, I identify:\n {circle_descriptions}. That totals {num_circles}, which is {parity}, so the final outcome is {parity}.",
    "By reasoning through the data, I see:\n {circle_descriptions}. This equals {num_circles}. Being {parity}, the conclusion is {parity}.",
    "Upon structured observation, I record:\n {circle_descriptions}. The number counted is {num_circles}, which is {parity}, hence the answer is {parity}.",
    "From logical analysis, I conclude:\n {circle_descriptions}. In sum, {num_circles}, which is {parity}, so the correct answer is {parity}.",
    "With stepwise reasoning, I list:\n {circle_descriptions}. Together they make {num_circles}, which is {parity}, so the solution is {parity}.",
    "Close evaluation reveals:\n {circle_descriptions}. This brings the total to {num_circles}, which is {parity}, and thus the result is {parity}.",
    "After detailed reasoning, I find:\n {circle_descriptions}. That totals {num_circles}, which is {parity}, so the conclusion is {parity}.",
    "A logical step shows:\n {circle_descriptions}. Therefore, the count is {num_circles}, which is {parity}, leading to {parity}.",
    "By counting logically, I detect:\n {circle_descriptions}. The sum is {num_circles}, which is {parity}, giving the final answer {parity}.",
    "On deeper inspection, I note:\n {circle_descriptions}. This amounts to {num_circles}. As it is {parity}, the answer is {parity}.",
    "Breaking down carefully, I observe:\n {circle_descriptions}. The total is {num_circles}, which is {parity}, hence the conclusion is {parity}.",
    "Logical reasoning suggests:\n {circle_descriptions}. That makes {num_circles} circles. Since that is {parity}, the answer is {parity}.",
    "After careful thinking, I count:\n {circle_descriptions}. The total is {num_circles}, which is {parity}, so the outcome is {parity}.",
    "From stepwise logic, I gather:\n {circle_descriptions}. The final count is {num_circles}, which is {parity}, therefore the result is {parity}.",
    "By analyzing thoroughly, I identify:\n {circle_descriptions}. This equals {num_circles}. As that is {parity}, the conclusion is {parity}.",
    "With reasoning applied, I see:\n {circle_descriptions}. They total {num_circles}, which is {parity}, so the answer must be {parity}.",
    "Stepwise observation shows:\n {circle_descriptions}. That equals {num_circles}, which is {parity}, and so the solution is {parity}.",
    "Through methodical review, I find:\n {circle_descriptions}. Their number is {num_circles}, which is {parity}, giving {parity} as the answer.",
    "By logical evaluation, I notice:\n {circle_descriptions}. Adding up results in {num_circles}, which is {parity}, therefore {parity} is correct.",
    "Analyzing systematically, I see:\n {circle_descriptions}. This comes to {num_circles}, which is {parity}, hence the result is {parity}.",
    "From stepwise examination, I observe:\n {circle_descriptions}. The sum is {num_circles}, which is {parity}, so the conclusion is {parity}.",
    "Detailed reasoning reveals:\n {circle_descriptions}. That totals {num_circles}, which is {parity}, therefore the output is {parity}.",
    "Breaking into steps, I note:\n {circle_descriptions}. This equals {num_circles}, which is {parity}, hence the result is {parity}.",
    "Reasoning carefully, I detect:\n {circle_descriptions}. Summing gives {num_circles}, which is {parity}, so the answer is {parity}.",
    "By analytical thinking, I list:\n {circle_descriptions}. These total {num_circles}, which is {parity}, leading to {parity}.",
    "Logical inspection shows:\n {circle_descriptions}. Adding them gives {num_circles}, which is {parity}, so the conclusion is {parity}.",
    "Upon thoughtful observation, I find:\n {circle_descriptions}. Thus, there are {num_circles}, which is {parity}, giving the result {parity}.",
    "Reasoning line by line, I observe:\n {circle_descriptions}. That produces {num_circles}, which is {parity}, so the outcome is {parity}.",
    "By structured reasoning, I identify:\n {circle_descriptions}. Their total number is {num_circles}, which is {parity}, therefore {parity} is correct.",
    "With logical breakdown, I conclude:\n {circle_descriptions}. In total, {num_circles}, which is {parity}, so the answer must be {parity}.",
    "Examining each carefully, I see:\n {circle_descriptions}. The overall count is {num_circles}, which is {parity}, and thus the final result is {parity}.",
    "Analyzing in sequence, I record:\n {circle_descriptions}. Their number is {num_circles}. As {num_circles} is {parity}, the answer is {parity}.",
    "Through thoughtful reasoning, I gather:\n {circle_descriptions}. That comes to {num_circles}. Since it’s {parity}, the result is {parity}.",
    "On deliberate observation, I observe:\n {circle_descriptions}. This equals {num_circles}, which is {parity}, therefore the conclusion is {parity}.",
    "Stepwise review reveals:\n {circle_descriptions}. That totals {num_circles}, which is {parity}, making the answer {parity}.",
    "From logical thought, I detect:\n {circle_descriptions}. This results in {num_circles}, which is {parity}, so the solution is {parity}.",
    "Analyzing critically, I list:\n {circle_descriptions}. Summing yields {num_circles}, which is {parity}, giving {parity} as the result.",
    "After clear reasoning, I note:\n {circle_descriptions}. This means {num_circles} circles. Since that’s {parity}, the output is {parity}.",
    "By structured analysis, I find:\n {circle_descriptions}. The total is {num_circles}, which is {parity}, leading to {parity}.",
    "Observing sequentially, I identify:\n {circle_descriptions}. Thus, {num_circles} circles in all, which is {parity}, so the result is {parity}.",
    "Logical inspection leads me to:\n {circle_descriptions}. Adding them gives {num_circles}, which is {parity}, hence the answer is {parity}.",
    "Stepwise analysis shows:\n {circle_descriptions}. This equals {num_circles}, which is {parity}, so the outcome is {parity}.",
    "Carefully tallying, I see:\n {circle_descriptions}. That makes {num_circles}, which is {parity}, therefore the conclusion is {parity}.",
    "With deliberate reasoning, I detect:\n {circle_descriptions}. Their number totals {num_circles}, which is {parity}, leading to {parity}.",
    "A reasoned approach shows:\n {circle_descriptions}. This adds up to {num_circles}, which is {parity}, and so the answer is {parity}.",
    "Breaking reasoning into steps, I conclude:\n {circle_descriptions}. The total is {num_circles}. As {num_circles} is {parity}, the result is {parity}.",
    "Upon precise reasoning, I list:\n {circle_descriptions}. Altogether, {num_circles}. Since that is {parity}, the solution is {parity}.",
    "From critical analysis, I observe:\n {circle_descriptions}. Their sum is {num_circles}, which is {parity}, hence the answer is {parity}.",
    "After logical review, I see:\n {circle_descriptions}. The total count is {num_circles}, which is {parity}, so the final answer is {parity}.",
    "Stepwise thought leads me to:\n {circle_descriptions}. That adds to {num_circles}. Since {num_circles} is {parity}, the result is {parity}.",
    "Careful logical reasoning shows:\n {circle_descriptions}. This produces {num_circles}, which is {parity}, giving the conclusion {parity}.",
    "From systematic breakdown, I record:\n {circle_descriptions}. Their number equals {num_circles}, which is {parity}, so the output is {parity}.",
    "By deliberate examination, I detect:\n {circle_descriptions}. Altogether {num_circles}, which is {parity}, hence the result is {parity}.",
    "Logical sequence shows:\n {circle_descriptions}. Therefore, the count is {num_circles}, which is {parity}, so the answer is {parity}.",
    "From reasoned observation, I conclude:\n {circle_descriptions}. That equals {num_circles}, which is {parity}, so the final outcome is {parity}.",
    "Step by step, I analyze:\n {circle_descriptions}. Adding them gives {num_circles}. Since {num_circles} is {parity}, the answer is {parity}.",
    "Looking logically, I identify:\n {circle_descriptions}. That sums to {num_circles}, which is {parity}, making the answer {parity}.",
    "Reasoning carefully, I see:\n {circle_descriptions}. Their total is {num_circles}, which is {parity}, so the conclusion is {parity}.",
    "From critical reasoning, I tally:\n {circle_descriptions}. This equals {num_circles}, which is {parity}, hence the solution is {parity}.",
]

cot_templates = cot_templates_grok + cot_templates_chatgpt